#!/bin/bash
#
# Generate filtered SPDX SBOM from Mix project.
#
# This script:
# 1. Runs mix sbom.cyclonedx to generate CycloneDX SBOM
# 2. Converts CycloneDX to SPDX JSON format
#    Note: Using custom converter as no standard tool is available for CDX->SPDX conversion
# 3. Filters the SPDX SBOM to include only production dependencies
#    Note: Custom filter to exclude test/dev dependencies
# 4. Generates a human-readable text report using spdx-tools (standard tool)
#
# Usage:
#   ./generate_sbom.sh [options]
#
# Options:
#   --output-dir DIR    Output directory for SBOM files (default: current directory)
#   --force            Force regeneration even if files exist
#   --skip-mix         Skip running mix sbom.cyclonedx (use existing bom.cdx.json)
#   --skip-convert     Skip conversion (use existing bom.spdx.json)
#   --skip-filter      Skip filtering (use existing bom.spdx.filtered.json)
#   --skip-report      Skip generating text report
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUT_DIR="${PROJECT_ROOT}"
FORCE=false
SKIP_MIX=false
SKIP_CONVERT=false
SKIP_FILTER=false
SKIP_REPORT=false

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --force)
            FORCE=true
            shift
            ;;
        --skip-mix)
            SKIP_MIX=true
            shift
            ;;
        --skip-convert)
            SKIP_CONVERT=true
            shift
            ;;
        --skip-filter)
            SKIP_FILTER=true
            shift
            ;;
        --skip-report)
            SKIP_REPORT=true
            shift
            ;;
        -h|--help)
            cat <<EOF
Generate filtered SPDX SBOM from Mix project.

Usage: $0 [options]

Options:
  --output-dir DIR    Output directory for SBOM files (default: project root)
  --force            Force regeneration even if files exist
  --skip-mix         Skip running mix sbom.cyclonedx (use existing bom.cdx.json)
  --skip-convert     Skip conversion (use existing bom.spdx.json)
  --skip-filter      Skip filtering (use existing bom.spdx.filtered.json)
  --skip-report      Skip generating text report
  -h, --help         Show this help message

Output files:
  - bom.cdx.json              CycloneDX SBOM (generated by mix sbom.cyclonedx)
  - bom.spdx.json             SPDX SBOM (converted from CycloneDX)
  - bom.spdx.filtered.json    Filtered SPDX SBOM (production dependencies only)
  - bom.spdx.filtered.txt     Human-readable text report
EOF
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            echo "Use --help for usage information" >&2
            exit 1
            ;;
    esac
done

# Change to project root for mix commands
cd "${PROJECT_ROOT}"

CDX_FILE="${OUTPUT_DIR}/bom.cdx.json"
SPDX_FILE="${OUTPUT_DIR}/bom.spdx.json"
FILTERED_FILE="${OUTPUT_DIR}/bom.spdx.filtered.json"
TEXT_REPORT_FILE="${OUTPUT_DIR}/bom.spdx.filtered.txt"
CONVERTER_SCRIPT="${SCRIPT_DIR}/convert_cdx_to_spdx.py"
FILTER_SCRIPT="${SCRIPT_DIR}/filter_and_enrich.py"
REPORT_SCRIPT="${SCRIPT_DIR}/generate_text_report.py"

# Check if converter script exists
if [[ ! -f "${CONVERTER_SCRIPT}" ]]; then
    echo "Error: Converter script not found: ${CONVERTER_SCRIPT}" >&2
    exit 1
fi

# Check if filter script exists
if [[ ! -f "${FILTER_SCRIPT}" ]]; then
    echo "Error: Filter script not found: ${FILTER_SCRIPT}" >&2
    exit 1
fi

# Check if report script exists
if [[ ! -f "${REPORT_SCRIPT}" ]]; then
    echo "Error: Report script not found: ${REPORT_SCRIPT}" >&2
    exit 1
fi

# Step 1: Generate CycloneDX SBOM
if [[ "${SKIP_MIX}" == "false" ]]; then
    if [[ -f "${CDX_FILE}" && "${FORCE}" == "false" ]]; then
        echo "CycloneDX SBOM already exists: ${CDX_FILE}" >&2
        echo "Use --force to regenerate or --skip-mix to use existing file" >&2
    else
        echo "Step 1/4: Generating CycloneDX SBOM..." >&2
        mix sbom.cyclonedx --output "${CDX_FILE}" --force
        echo "✓ CycloneDX SBOM generated: ${CDX_FILE}" >&2
    fi
    else
    echo "Step 1/4: Skipping mix sbom.cyclonedx (using existing file)" >&2
fi

if [[ ! -f "${CDX_FILE}" ]]; then
    echo "Error: CycloneDX SBOM file not found: ${CDX_FILE}" >&2
    exit 1
fi

# Step 2: Convert CycloneDX to SPDX
if [[ "${SKIP_CONVERT}" == "false" ]]; then
    if [[ -f "${SPDX_FILE}" && "${FORCE}" == "false" ]]; then
        echo "SPDX SBOM already exists: ${SPDX_FILE}" >&2
        echo "Use --force to regenerate or --skip-convert to use existing file" >&2
    else
        echo "Step 2/4: Converting CycloneDX to SPDX..." >&2
        python3 "${CONVERTER_SCRIPT}" "${CDX_FILE}" -o "${SPDX_FILE}"
        echo "✓ SPDX SBOM converted: ${SPDX_FILE}" >&2
    fi
    else
    echo "Step 2/4: Skipping conversion (using existing file)" >&2
fi

if [[ ! -f "${SPDX_FILE}" ]]; then
    echo "Error: SPDX SBOM file not found: ${SPDX_FILE}" >&2
    exit 1
fi

# Step 3: Filter SPDX SBOM
if [[ "${SKIP_FILTER}" == "false" ]]; then
    if [[ -f "${FILTERED_FILE}" && "${FORCE}" == "false" ]]; then
        echo "Filtered SPDX SBOM already exists: ${FILTERED_FILE}" >&2
        echo "Use --force to regenerate or --skip-filter to use existing file" >&2
    else
        echo "Step 3/4: Filtering SPDX SBOM..." >&2
        python3 "${FILTER_SCRIPT}" \
            --sbom "${SPDX_FILE}" \
            --output "${FILTERED_FILE}" \
            --lib-dir "${PROJECT_ROOT}/_build/emqx-enterprise/rel/emqx/lib" \
            --deps-dir "${PROJECT_ROOT}/deps"
        echo "✓ Filtered SPDX SBOM generated: ${FILTERED_FILE}" >&2
    fi
    else
    echo "Step 3/4: Skipping filtering (using existing file)" >&2
fi

if [[ ! -f "${FILTERED_FILE}" ]]; then
    echo "Error: Filtered SPDX SBOM file not found: ${FILTERED_FILE}" >&2
    exit 1
fi

# Step 4: Generate text report
if [[ "${SKIP_REPORT}" == "false" ]]; then
    if [[ -f "${TEXT_REPORT_FILE}" && "${FORCE}" == "false" ]]; then
        echo "Text report already exists: ${TEXT_REPORT_FILE}" >&2
        echo "Use --force to regenerate or --skip-report to skip" >&2
    else
        echo "Step 4/4: Generating text report..." >&2
        python3 "${REPORT_SCRIPT}" "${FILTERED_FILE}" -o "${TEXT_REPORT_FILE}"
        echo "✓ Text report generated: ${TEXT_REPORT_FILE}" >&2
    fi
else
    echo "Step 4/4: Skipping text report generation" >&2
fi

echo "" >&2
echo "✓ SBOM generation complete!" >&2
echo "" >&2
echo "Generated files:" >&2
echo "  - ${CDX_FILE}" >&2
echo "  - ${SPDX_FILE}" >&2
echo "  - ${FILTERED_FILE}" >&2
if [[ -f "${TEXT_REPORT_FILE}" ]]; then
    echo "  - ${TEXT_REPORT_FILE}" >&2
fi
