name: 'Prepare jmeter'
description: 'Download jmeter packages'
runs:
  using: composite
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: emqx/emqx-fvt
        ref: broker-autotest-v5
        path: scripts
    - uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: '8.0.282' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
        # https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md
        distribution: 'zulu'
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
      with:
        name: apache-jmeter.tgz
    - name: install jmeter
      shell: bash
      env:
        JMETER_VERSION: 5.4.3
      run: |
        tar -xf apache-jmeter.tgz
        ln -s apache-jmeter-$JMETER_VERSION jmeter
        echo "jmeter.save.saveservice.output_format=xml" >> jmeter/user.properties
        echo "jmeter.save.saveservice.response_data.on_error=true" >> jmeter/user.properties
        cd jmeter/lib/ext
        wget --no-verbose https://raw.githubusercontent.com/xmeter-net/mqtt-jmeter/master/Download/v2.0.2/mqtt-xmeter-fuse-2.0.2-jar-with-dependencies.jar
        wget --no-verbose https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.16/mysql-connector-java-8.0.16.jar
        wget --no-verbose https://repo1.maven.org/maven2/org/postgresql/postgresql/42.2.18/postgresql-42.2.18.jar
