name: 'Detect profiles'
inputs:
  ci_git_token:
    required: true
    type: string
outputs:
  profiles:
    description: 'Detected profiles'
    value: ${{ steps.detect-profiles.outputs.profiles}}

runs:
  using: composite
  steps:
    - id: detect-profiles
      shell: bash
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        if make emqx-ee --dry-run > /dev/null 2>&1; then
          echo "::set-output name=profiles::[\"emqx-ee\"]"
          echo "https://ci%40emqx.io:${{ inputs.ci_git_token }}@github.com" > $HOME/.git-credentials
          git config --global credential.helper store
          echo "EMQX_NAME=emqx-ee" >> $GITHUB_ENV
        else
          echo "::set-output name=profiles::[\"emqx\", \"emqx-edge\"]"
          echo "EMQX_NAME=emqx" >> $GITHUB_ENV
        fi
