defmodule Mix.Tasks.Emqx.CheckClusterRpc do
  use Mix.Task

  @shortdoc "Check emqx_cluster_rpc:multicall targets against an exemption list"

  @moduledoc """
  Check that no new `emqx_cluster_rpc:multicall` target is added without an
  explicit exemption.

  ## Why this check exists

  `emqx_cluster_rpc:multicall` appends the MFA to the cluster_rpc log. A node
  that boots after downtime does not replay the log entries it missed:
  `emqx_conf_app:init_load/1` copies the cluster config from a peer and
  `emqx_cluster_rpc:maybe_init_tnx_id/2` fast-forwards the node's commit
  pointer past them. Any MFA effect that is not recoverable from the copied
  config or from a replicated mria table is silently lost on that node.

  ## Rules for a multicall target

  - Config updates (`emqx:update_config` and friends) are safe: the boot-time
    config copy recovers them.
  - Any other target must write durable state to config or mria BEFORE the
    multicall, and use the MFA only to rebuild node-local runtime state. A
    skipped replay is then harmless because boot rebuilds runtime state from
    the replicated data. See `emqx_topic_metrics_registry` for the reference
    pattern and `emqx_mt_config` for another compliant example.

  If a new target follows these rules, add `{Module, Function}` to
  `@exemptions` below with a comment explaining why a skipped replay is safe.
  Remove entries whose call sites are gone.

  ## How it works

  xref over the compiled umbrella apps yields every caller of
  `emqx_cluster_rpc:multicall/3,5`; the caller's `bpapi_meta/0` (generated by
  the `emqx_bpapi_trans` parse transform, which only accepts literal target
  atoms) yields the target MFA.

  ## Scope

  Umbrella apps and in-tree plugins are checked. Plugins are separate mix
  projects outside the umbrella build; their beams are loaded from the shared
  build tree (plugin mix.exs sets `build_path: "../../_build"`). Run
  `scripts/build-plugins.sh --compile-only` (as the static_checks make target
  does) or `make plugins` to produce them. A plugin caller must follow the
  same target rules as an umbrella caller, but plugins cannot host BPAPI
  proto modules, so an audited plugin caller is exempted by module name via
  `@exempted_callers` instead. A plugin caller must additionally accept that
  a live node where the plugin app is not running fails the apply and retries
  until the plugin starts — the boot path is unaffected because catch-up
  fast-forwards past missed entries and plugin boot rebuilds runtime state
  from replicated tables.
  """

  @requirements ["compile", "loadpaths"]

  @xref __MODULE__

  # Safe by design: the boot-time cluster config copy recovers the effect of
  # these targets on a node that missed them.
  @config_targets [
    {:emqx, :update_config},
    {:emqx, :remove_config},
    {:emqx, :reset_config}
  ]

  # Grandfathered or audited targets. Each entry needs a reason.
  @exemptions [
    # KNOWN DEFECT: plugin package delete / start / stop is lost on a node
    # that reboots after missing the transaction. The plugin survives on disk
    # there and resurfaces in the cluster-wide API. Do not copy this pattern.
    {:emqx_mgmt_api_plugins, :delete_package},
    {:emqx_mgmt_api_plugins, :ensure_action},
    # Audited safe: durable state goes to mria first; these MFAs only rebuild
    # persistent_term limiter groups, and boot re-derives them via
    # `emqx_mt_config:load/0`.
    {:emqx_mt_config, :execute_side_effects_v1},
    {:emqx_mt_config, :cleanup_managed_ns_configs_v1},
    # Metrics resets: a skipped replay loses only a counter reset.
    {:emqx_resource, :reset_metrics_local},
    {:emqx_rule_engine, :reset_metrics_for_rule}
  ]

  # Audited direct callers. Plugins cannot host BPAPI proto modules, so their
  # multicall targets cannot be resolved via bpapi_meta/0; the whole caller
  # module is exempted instead. Each entry needs a reason.
  # (No entries on this branch; see the emqx_unsgov exemption on dev-61+.)
  @exempted_callers []

  @impl true
  def run(args) do
    if args != [] do
      Mix.raise("Unknown options:\n  #{inspect(args, pretty: true)}")
    end

    callers = find_multicall_callers()
    :xref.stop(@xref)
    {violations, targets} = Enum.reduce(callers, {[], []}, &collect/2)
    stale = @exemptions -- targets
    stale_callers = @exempted_callers -- Enum.map(callers, &elem(&1, 0))
    Enum.each(Enum.reverse(violations), &report_violation/1)
    Enum.each(stale, &report_stale/1)
    Enum.each(stale_callers, &report_stale_caller/1)

    if violations == [] and stale == [] and stale_callers == [] do
      Mix.shell().info("OK")
    else
      Mix.raise(
        "emqx_cluster_rpc:multicall target check failed; see `mix help emqx.check_cluster_rpc`"
      )
    end
  end

  defp find_multicall_callers() do
    ensure_xref()

    Mix.Dep.Umbrella.cached()
    |> Enum.each(fn app ->
      {:ok, _} = :xref.add_application(@xref, to_charlist(app.opts[:build]))
    end)

    for ebin_dir <- plugin_ebin_dirs() do
      # The beams must be loadable to read a plugin proto module's bpapi_meta/0:
      true = Code.append_path(ebin_dir)
      {:ok, _} = :xref.add_directory(@xref, to_charlist(ebin_dir))
    end

    query = ~c"XC || [emqx_cluster_rpc:multicall/3, emqx_cluster_rpc:multicall/5]"

    case :xref.q(@xref, query) do
      {:ok, pairs} ->
        for {caller = {m, _f, _a}, _callee} <- pairs,
            m != :emqx_cluster_rpc,
            uniq: true do
          caller
        end

      {:error, :xref_compiler, {:unknown_constant, const}} ->
        Mix.raise("#{const} is not in the analyzed applications; wrong build?")
    end
  end

  # In-tree plugins are not part of the umbrella build: load their beams from
  # the shared build tree, where the plugin build (scripts/build-plugins.sh
  # --compile-only, run by the static_checks make target) puts them.
  defp plugin_ebin_dirs() do
    for plugin_dir <- Path.wildcard("plugins/*"),
        plugin_app?(plugin_dir) do
      ebin_dir = Path.join([Mix.Project.build_path(), "lib", Path.basename(plugin_dir), "ebin"])

      if Path.wildcard(Path.join(ebin_dir, "*.beam")) == [] do
        Mix.raise(
          "no beams for plugin #{plugin_dir} in #{ebin_dir}; " <>
            "run 'scripts/build-plugins.sh --compile-only' first"
        )
      end

      ebin_dir
    end
  end

  defp plugin_app?(plugin_dir) do
    mix_exs = Path.join(plugin_dir, "mix.exs")
    File.exists?(mix_exs) and File.read!(mix_exs) =~ "emqx_plugin:"
  end

  # Resolve a multicall caller to its target {m, f} via the metadata that
  # `emqx_bpapi_trans` generated for the proto module.
  defp collect(caller = {m, f, a}, {violations, targets}) do
    case bpapi_meta(m) do
      %{calls: calls} ->
        caller_targets =
          for {{^m, ^f, from_args}, {tm, tf, _t_args}} <- calls,
              length(from_args) == a do
            {tm, tf}
          end

        case caller_targets do
          [] ->
            {[{:no_meta_entry, caller} | violations], targets}

          _ ->
            new = Enum.reject(caller_targets, &allowed?/1)

            {
              Enum.map(new, &{:new_target, &1, caller}) ++ violations,
              caller_targets ++ targets
            }
        end

      _ ->
        if Enum.member?(@exempted_callers, m) do
          {violations, targets}
        else
          {[{:not_a_proto_module, caller} | violations], targets}
        end
    end
  end

  defp bpapi_meta(mod) do
    apply(mod, :bpapi_meta, [])
  rescue
    _ -> :undefined
  end

  defp allowed?(target) do
    Enum.member?(@config_targets ++ @exemptions, target)
  end

  defp report_violation({:new_target, {m, f}, {cm, cf, ca}}) do
    Mix.shell().error(
      "new emqx_cluster_rpc:multicall target #{m}:#{f} (called from #{cm}:#{cf}/#{ca}); " <>
        "a node that reboots after missing this transaction will not replay it"
    )
  end

  defp report_violation({:not_a_proto_module, {m, f, a}}) do
    Mix.shell().error(
      "#{m}:#{f}/#{a} calls emqx_cluster_rpc:multicall but is not a BPAPI proto module"
    )
  end

  defp report_violation({:no_meta_entry, {m, f, a}}) do
    Mix.shell().error(
      "cannot determine the emqx_cluster_rpc:multicall target of #{m}:#{f}/#{a} " <>
        "from its bpapi_meta/0"
    )
  end

  defp report_stale({m, f}) do
    Mix.shell().error("stale exemption #{m}:#{f} has no call site; remove it from this task")
  end

  defp report_stale_caller(m) do
    Mix.shell().error(
      "stale exempted caller #{m} no longer calls emqx_cluster_rpc:multicall; " <>
        "remove it from this task"
    )
  end

  defp ensure_xref() do
    case :xref.start(@xref) do
      {:ok, _} ->
        :ok = :xref.set_default(@xref, warnings: false)

      {:error, {:already_started, _}} ->
        :xref.stop(@xref)
        ensure_xref()
    end
  end
end
