--------------------------------------------------------------------------
-- Copyright (c) 2025 EMQ Technologies Co., Ltd. All Rights Reserved.
--------------------------------------------------------------------------

-- A collection of ASN.1 definitions encoding various types related to
-- the builtin backends that may at some point end up stored
-- persistently on disk.
DSBuiltinMetadata DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
  TopicWords ::= SEQUENCE OF OCTET STRING

  -- emqx_ds_storage_skipstream_lts
  StreamSkipstreamLtsV1 ::= OCTET STRING

  ItSkipstreamV1 ::= SEQUENCE {
    static OCTET STRING,
    lastKey INTEGER,
    compressedTf OCTET STRING
  }

  -- Generic definitions (local and Raft)
  --   Stream:
  StorageStream ::= CHOICE {
    skipstreamLtsV1 StreamSkipstreamLtsV1,
    ...
  }

  Stream ::= SEQUENCE {
    shard OCTET STRING,
    generation INTEGER,
    inner StorageStream
  }

  --   Iterator:
  StorageIterator ::= CHOICE {
    skipstreamLtsV1 ItSkipstreamV1,
    ...
  }

  Iterator ::= SEQUENCE {
    shard OCTET STRING,
    generation INTEGER,
    inner StorageIterator
  }
END
