# Configuration for weekly-digest - https://github.com/apps/weekly-digest
publishDay: monday
canPublishIssues: true
canPublishPullRequests: true
canPublishContributors: true
canPublishStargazers: true
canPublishCommits: true
