#!/bin/bash

make fmt > /dev/null &>1 &

./rebar3 ct --name ct@127.0.0.1 --readable=true  --suite ./_build/test/lib/emqx/test/emqx_persistent_session_SUITE.beam --case t_publish_while_client_is_gone_qos1 --group tcp

suites=$(cat <<EOF | paste -sd "," -
./_build/test/lib/emqx/test/emqx_persistent_session_SUITE.beam
./_build/test/lib/emqx/test/emqx_persistent_messages_SUITE.beam
EOF
)

#./rebar3 ct --name ct@127.0.0.1 --readable=true --suite "${suites}" --case t_publish_while_client_is_gone
