#!/bin/sh

rm -rf temp

mkdir temp

echo 01 > temp/serial
touch temp/index.txt

## create ca certificate
openssl req -x509 -config openssl.cnf -newkey rsa:2048 -days 365  -out cacert.pem -outform PEM -subj /CN=MyTestCA/ -nodes
openssl x509 -in cacert.pem -out temp/cacert.cer -outform DER

## create server certificate
openssl genrsa -out server-key.pem 2048
openssl req -new -key server-key.pem -out temp/server-req.pem -outform PEM -subj /CN=$(hostname)/O=server/ -nodes
openssl ca -config openssl.cnf -in temp/server-req.pem -out server-cert.pem -notext -batch -extensions server_ca_extensions

## create client certificate
openssl genrsa -out client-key.pem 2048
openssl req -new -key client-key.pem -out temp/client-req.pem -outform PEM -subj /CN=$(hostname)/O=client/ -nodes
openssl ca -config openssl.cnf -in temp/client-req.pem -out client-cert.pem -notext -batch -extensions client_ca_extensions

rm -rf temp