#!/usr/bin/env bash
#
# make-fake-target.sh — produce a minimal fake EMQX target tarball
# and a matching no-op .relup catalog entry. The tarball is
# written wherever the operator wants (defaults to the running rel
# tree's data dir) — the relup plugin no longer cares about a
# specific staging directory; it reads the path passed to `emqx ctl
# relup upgrade <TarballPath>` directly.
#
# Reads the running EMQX's vsn + BUILD_INFO from the assembled
# release tree under _build/$PROFILE/rel/emqx and forges a target
# whose erlang/os/arch values match (so the handler's compatibility
# checks pass) and whose `releases/emqx_vars` carries the right
# `REL_VSN="..."` line (so the handler can read the target version).
#
# Usage:
#   plugins/emqx_relup/test/fixtures/make-fake-target.sh [TARGET_VSN] [DEST_DIR]
#
# TARGET_VSN defaults to "<currvsn>-fake".
# DEST_DIR   defaults to "$REL_DIR/data" so the smoke is self-
#            contained; pass `/tmp` (or anywhere) to model an
#            operator-chosen staging path.

set -euo pipefail

PROFILE="${PROFILE:-emqx-enterprise}"
REPO_ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
REL_DIR="$REPO_ROOT/_build/$PROFILE/rel/emqx"

if [ ! -d "$REL_DIR" ]; then
    echo "fatal: $REL_DIR not found — run 'make' first" >&2
    exit 1
fi

CURR_VSN="$(awk '{print $2}' "$REL_DIR/releases/start_erl.data")"
CURR_BUILD_INFO="$REL_DIR/releases/$CURR_VSN/BUILD_INFO"
ERTS_VSN="$(awk '{print $1}' "$REL_DIR/releases/start_erl.data")"
TARGET_VSN="${1:-${CURR_VSN}-fake}"
DEST_DIR="${2:-$REL_DIR/data}"

OS_LINE="$(grep '^os:' "$CURR_BUILD_INFO" | head -1)"
ARCH_LINE="$(grep '^arch:' "$CURR_BUILD_INFO" | head -1)"
ERL_LINE="$(grep '^erlang:' "$CURR_BUILD_INFO" | head -1)"

OS_VAL="$(echo "$OS_LINE" | cut -d: -f2- | xargs)"
ARCH_VAL="$(echo "$ARCH_LINE" | cut -d: -f2- | xargs)"

STAGE="$(mktemp -d -t emqx-relup-fake.XXXXXX)"
trap 'rm -rf "$STAGE"' EXIT

# --- forge the fake target tarball ---
TGT_RELEASES="$STAGE/releases/$TARGET_VSN"
mkdir -p "$TGT_RELEASES"
cat > "$TGT_RELEASES/emqx.rel" <<EOF
{release, {"emqx", "$TARGET_VSN"}, {erts, "$ERTS_VSN"}, []}.
EOF
{
    echo "$ERL_LINE"
    echo "$OS_LINE"
    echo "$ARCH_LINE"
} > "$TGT_RELEASES/BUILD_INFO"

# releases/emqx_vars carries REL_VSN — the handler reads this to
# learn the target version (replaces the old .target_vsn sidecar).
cat > "$STAGE/releases/emqx_vars" <<EOF
REL_VSN="$TARGET_VSN"
ERTS_VSN="$ERTS_VSN"
EOF

# mnesia_hook.beam presence is the EMQX-fork sentinel (assert_same_otp_fork)
MNESIA_DIR="$(find "$REL_DIR/lib" -maxdepth 1 -type d -name 'mnesia-*' 2>/dev/null | head -1)"
if [ -n "$MNESIA_DIR" ]; then
    REL_MNESIA="$(basename "$MNESIA_DIR")"
    mkdir -p "$STAGE/lib/$REL_MNESIA/ebin"
    if [ -f "$MNESIA_DIR/ebin/mnesia_hook.beam" ]; then
        cp "$MNESIA_DIR/ebin/mnesia_hook.beam" "$STAGE/lib/$REL_MNESIA/ebin/"
    else
        : > "$STAGE/lib/$REL_MNESIA/ebin/mnesia_hook.beam"
    fi
fi

TAR_NAME="emqx-${PROFILE#emqx-}-${TARGET_VSN}-${OS_VAL}-${ARCH_VAL}.tar.gz"
mkdir -p "$DEST_DIR"
TAR_PATH="$DEST_DIR/$TAR_NAME"
tar -C "$STAGE" -czf "$TAR_PATH" .
SHA256="$(sha256sum "$TAR_PATH" | awk '{print $1}')"
echo "$SHA256" > "$TAR_PATH.sha256"

# --- write the no-op .relup catalog entry ---
RELUP_DIR="$REPO_ROOT/plugins/emqx_relup/priv/relup"
mkdir -p "$RELUP_DIR"
RELUP_FILE="$RELUP_DIR/${CURR_VSN}-to-${TARGET_VSN}.relup"
cat > "$RELUP_FILE" <<EOF
%% Auto-generated by test/fixtures/make-fake-target.sh — no-op smoke hop.
#{
    from_version => "$CURR_VSN",
    target_version => "$TARGET_VSN",
    code_changes => [],
    post_upgrade_callbacks => []
}.
EOF

cat <<EOF
staged target tarball: $TAR_PATH
sha256 sidecar:        $TAR_PATH.sha256
catalog entry:       $RELUP_FILE
to drive the smoke:
  $REL_DIR/bin/emqx ctl relup list-supported-paths
  $REL_DIR/bin/emqx ctl relup upgrade $TAR_PATH
EOF
