DurableSession DEFINITIONS ::=
BEGIN
  ID ::= INTEGER(0..MAX)

  TopicFilter ::= SEQUENCE {
    topic [0] OCTET STRING,
    group [1] OCTET STRING OPTIONAL
  }

  Subscription ::= SEQUENCE {
    id [0] ID,
    currentState [1] ID,
    startTime [2] INTEGER,
    ...
  }

  Misc ::= SEQUENCE {
    key [0] OCTET STRING,
    val [1] OCTET STRING
  }

  SubState ::= SEQUENCE {
    parentSub [0] ID,
    -- Flags
    upgradeQos [1] BOOLEAN,
    durable [2] BOOLEAN,
    --
    supersededBy [3] ID OPTIONAL,
    shareTopicFilter [4] TopicFilter OPTIONAL,
    --
    miscSubopts [5] SEQUENCE OF Misc,
    ...
  }

  StreamKey ::= SEQUENCE {
    subId [0] ID,
    stream [1] OCTET STRING
  }

  SRS ::= SEQUENCE {
    shard [0] OCTET STRING,
    generation [1] INTEGER,
    itBegin [2] OCTET STRING,
    -- Strictly speaking, we don't have to store itEnd, as can be
    -- derived from batchSize and itBegin. It's used as for some
    -- checks, so it's worth having.
    itEnd [3] OCTET STRING OPTIONAL,
    batchSize [4] INTEGER,
    firstSeqNoQoS1 [5] INTEGER,
    firstSeqNoQoS2 [6] INTEGER,
    lastSeqNoQoS1 [7] INTEGER,
    lastSeqNoQoS2 [8] INTEGER,
    unsubscribed [9] BOOLEAN,
    subscriptionState [10] ID,
    ...
  }
END
