services:
  redis_server_tls:
    container_name: redis-tls
    image: public.ecr.aws/docker/library/redis:${REDIS_TAG}
    volumes:
      - ./certs/cert.pem:/etc/certs/redis.crt
      - ./certs/key.pem:/etc/certs/redis.key
      - ./certs/cacert.pem:/etc/certs/ca.crt
      - ./redis/single-tls:/usr/local/etc/redis
    ports:
      - "6380:6380"
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      emqx_bridge:
