{
 "title": "EMQ details",
 "tags": [ "emqx" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(emqx_connections_count, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(emqx_connections_count{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_connections_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_connections_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_sessions_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_sessions_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Subscribers and suboptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_suboptions_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Subopt-Current"
    },
    {
     "expr": "emqx_suboptions_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Subopt-Max"
    },
    {
     "expr": "emqx_subscribers_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Suber-Current"
    },
    {
     "expr": "emqx_subscribers_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Suber-Max"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_subscriptions_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Normal-Current"
    },
    {
     "expr": "emqx_subscriptions_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Normal-Max"
    },
    {
     "expr": "emqx_subscriptions_shared_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Shared-Current"
    },
    {
     "expr": "emqx_subscriptions_shared_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Shared-Max"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_routes_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_routes_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Retained messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_retained_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "emqx_retained_max{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Messages overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(emqx_messages_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(emqx_messages_retained{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_retained{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Retained"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_dropped{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Dropped"
    },
    {
     "expr": "sum(rate(emqx_messages_delayed{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_delayed{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delayed"
    },
    {
     "expr": "sum(rate(emqx_messages_forward{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_forward{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Forward"
    }
   ]
  },
  {
   "title": "Messages/delivery dropped",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_dropped{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_dropped{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Message.Dropped"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped_expired {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_dropped_expired {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Message.Dropped.Expired"
    },
    {
     "expr": "sum(rate(emqx_messages_dropped_no_subscribers {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_dropped_no_subscribers {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Message.Dropped.no_subscribers"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_no_local{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped_no_local {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped.no_local"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_too_large {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped_too_large {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped.too_large"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_qos0_msg {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped_qos0_msg {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped.qos0_msg"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_queue_full {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped_queue_full {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped.queue_full"
    },
    {
     "expr": "sum(rate(emqx_delivery_dropped_expired {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_delivery_dropped_expired {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Delivery.Dropped.expired"
    }
   ]
  },
  {
   "title": "Messages received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(rate(emqx_messages_qos0_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos0_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received.QoS0"
    },
    {
     "expr": "sum(rate(emqx_messages_qos1_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos1_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received.QoS1"
    },
    {
     "expr": "sum(rate(emqx_messages_qos2_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos2_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Received.QoS2"
    }
   ]
  },
  {
   "title": "Messages  sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent"
    },
    {
     "expr": "sum(rate(emqx_messages_qos0_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos0_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent.QoS0"
    },
    {
     "expr": "sum(rate(emqx_messages_qos1_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos1_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent.QoS1"
    },
    {
     "expr": "sum(rate(emqx_messages_qos2_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_messages_qos2_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Sent.QoS2"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_bytes_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_bytes_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  },
  {
   "title": "Packets connect",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(emqx_packets_connect{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Connect"
    },
    {
     "expr": "rate(emqx_packets_connack_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Connack sent"
    },
    {
     "expr": "rate(emqx_packets_disconnect_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Disconnect sent"
    },
    {
     "expr": "rate(emqx_packets_connack_error {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "connack_error"
    },
    {
     "expr": "rate(emqx_packets_connack_auth_error {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "connack_auth_error"
    },
    {
     "expr": "rate(emqx_packets_auth_received {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Auth"
    },
    {
     "expr": "rate(emqx_packets_auth_sent {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Auth sent"
    }
   ]
  },
  {
   "title": "Packets subscribe/unsubscribe",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(emqx_packets_subscribe_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Subscribe received"
    },
    {
     "expr": "rate(emqx_packets_suback_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Suback sent"
    },
    {
     "expr": "rate(emqx_packets_unsubscribe_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unsubscribe received"
    },
    {
     "expr": "rate(emqx_packets_unsuback_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Unsuback sent"
    },
    {
     "expr": "rate(emqx_packets_subscribe_auth_error {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sub_auth_error"
    },
    {
     "expr": "rate(emqx_packets_subscribe_error {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "sub_error"
    },
    {
     "expr": "rate(emqx_packets_unsubscribe_error {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "unsub_error"
    }
   ]
  },
  {
   "title": "Packets ping",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_packets_pingreq_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_packets_pingreq_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Pingreq sent"
    },
    {
     "expr": "sum(rate(emqx_packets_pingresp_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(emqx_packets_pingresp_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Pingresp sent"
    }
   ]
  },
  {
   "title": "Packets publish",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(emqx_packets_publish_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Publish received"
    },
    {
     "expr": "rate(emqx_packets_publish_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Publish sent"
    },
    {
     "expr": "rate(emqx_packets_puback_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Puback received"
    },
    {
     "expr": "rate(emqx_packets_puback_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Puback sent"
    },
    {
     "expr": "rate(emqx_packets_pubrel_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pubrel received"
    },
    {
     "expr": "rate(emqx_packets_pubrel_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pubrel sent"
    },
    {
     "expr": "rate(emqx_packets_pubcomp_received{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pubcomp received"
    },
    {
     "expr": "rate(emqx_packets_pubcomp_sent{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Pubcomp sent"
    }
   ]
  }
 ]
}