{
 "title": "EMQ overview",
 "tags": [ "emqx" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(emqx_cluster_nodes_running, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(emqx_cluster_nodes_running{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(emqx_connections_count{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "Clients"
    },
    {
     "expr": "sum(rate(emqx_client_connected{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "connected rate"
    },
    {
     "expr": "sum(rate(emqx_client_disconnected{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "disconnected rate"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_messages_received{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(emqx_messages_sent{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_routes_count{instance=~\"$instance\",job=~\"$job\"}\nor emqx_topics_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Topics"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "emqx_subscriptions_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Subscriptions"
    },
    {
     "expr": "emqx_subscriptions_shared_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Shared Subscriptions"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(emqx_bytes_received{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Bytes received"
    },
    {
     "expr": "sum(rate(emqx_bytes_sent{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "Bytes sent"
    }
   ]
  }
 ]
}