{
 "title": "ErlangVM",
 "tags": [
  "emqx",
  "erlang"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(erlang_vm_process_count, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(erlang_vm_process_count{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "The CPU usage for the hosted machine",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "emqx_vm_cpu_use{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "emqx_vm_cpu_idle {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "idle"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "The memory usage for the hosted machine",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "emqx_vm_total_memory{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "emqx_vm_used_memory{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "VM memory",
   "type": "timeseries",
   "description": "The total amount of memory currently allocated.\nThis is the same as the sum of the memory size for processes and system.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Memory processes",
   "type": "timeseries",
   "description": "The total amount of memory currently allocated for the Erlang processes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_processes_bytes_total{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{usage}}"
    }
   ]
  },
  {
   "title": "Memory system",
   "type": "timeseries",
   "description": "The total amount of memory currently allocated for the emulator that is not directly related to any Erlang process.\nMemory presented as processes is not included in this memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_system_bytes_total{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{usage}}"
    }
   ]
  },
  {
   "title": "Processor  scheduler and threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "erlang_vm_logical_processors {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "logical-processors"
    },
    {
     "expr": "erlang_vm_logical_processors_available {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "logical-processors-avai"
    },
    {
     "expr": "erlang_vm_logical_processors_online {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "logical-processors-online"
    },
    {
     "expr": "erlang_vm_schedulers {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "schedulers"
    },
    {
     "expr": "erlang_vm_schedulers_online {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "schedulers-online"
    },
    {
     "expr": "erlang_vm_threads {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "vm_threads"
    },
    {
     "expr": "erlang_vm_thread_pool_size  {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "vm_thread_pool_size"
    },
    {
     "expr": "emqx_vm_run_queue {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "vm_run_queue"
    }
   ]
  },
  {
   "title": "System limit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "erlang_vm_ets_limit {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "ETS max"
    },
    {
     "expr": "erlang_vm_ets_tables {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "ETS count"
    },
    {
     "expr": "erlang_vm_dets_tables {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "DETS count"
    },
    {
     "expr": "erlang_vm_process_limit {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process max"
    },
    {
     "expr": "erlang_vm_process_count {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process count"
    },
    {
     "expr": "erlang_vm_port_limit {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Port max"
    },
    {
     "expr": "erlang_vm_port_count {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Port count"
    },
    {
     "expr": "erlang_vm_smp_support {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "smp_support"
    },
    {
     "expr": "erlang_vm_time_correction {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "time_correction"
    }
   ]
  },
  {
   "title": "VM statistics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(erlang_vm_statistics_context_switches{job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "context_switches"
    },
    {
     "expr": "rate(erlang_vm_statistics_garbage_collection_number_of_gcs {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "garbage_collection_number_of_gcs"
    },
    {
     "expr": "rate(erlang_vm_statistics_garbage_collection_bytes_reclaimed {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "garbage_collection_bytes_reclaimed"
    },
    {
     "expr": "rate(erlang_vm_statistics_bytes_received_total {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "bytes_received_total"
    },
    {
     "expr": "rate(erlang_vm_statistics_bytes_output_total {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "bytes_output_total"
    },
    {
     "expr": "rate(erlang_vm_statistics_reductions_total {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "reductions"
    },
    {
     "expr": "rate(erlang_vm_statistics_runtime_milliseconds {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "runtime_milliseconds"
    },
    {
     "expr": "rate(erlang_vm_statistics_wallclock_time_milliseconds {job=~\"$job\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "wallclock_time_milliseconds"
    }
   ]
  },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "erlang_vm_process_count{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Process count"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Run queue length"
    }
   ]
  },
  {
   "title": "Mnesia",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "erlang_mnesia_lock_queue{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Lock queue"
    },
    {
     "expr": "erlang_mnesia_held_locks{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Held locks"
    },
    {
     "expr": "erlang_mnesia_transaction_coordinators{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Transaction coordinators"
    },
    {
     "expr": "erlang_mnesia_transaction_participants {job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "Transaction participants"
    }
   ]
  },
  {
   "title": "Mnesia transaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(erlang_mnesia_committed_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(erlang_mnesia_committed_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(rate(erlang_mnesia_failed_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(erlang_mnesia_failed_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(erlang_mnesia_restarted_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(erlang_mnesia_restarted_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Restart"
    },
    {
     "expr": "sum(rate(erlang_mnesia_logged_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]) or irate(erlang_mnesia_logged_transactions {job=~\"$job\", instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Logged"
    }
   ]
  }
 ]
}