%%--------------------------------------------------------------------
%% Copyright (c) 2026 EMQ Technologies Co., Ltd. All Rights Reserved.
%%--------------------------------------------------------------------

-module(emqx_broker_heal).
-moduledoc """
This module implements a helper process that recovers clients' global
representation after a network partition.

It solves the following problem: when a cluster recovers after a
partition, mnesia tables are brought into a consistent state by
replacing their contents on the loser partition with the contents of
the winning partition. This may lead to the loss of data, esp. written
by the replicant nodes.

This process notifies all locally registered clients in the cluster,
forcing them to re-register globally. This is done in a rate-limited
fashion.

Limitations:

- Only state the living channels is updated.
  Deleted channels may linger in the global registry after heal is done.
""".

-behaviour(gen_server).

%% API:
-export([start_local/1, on_autoheal/1]).

%% behavior callbacks:
-export([init/1, handle_call/3, handle_continue/2, handle_cast/2, handle_info/2, terminate/2]).

%% internal exports:
-export([start_link/0]).

-export_type([]).

-include("emqx_cm.hrl").

%%================================================================================
%% Type declarations
%%================================================================================

-define(SERVER, ?MODULE).
-define(alarm, broker_heal).
-define(to_next, to_next).

%%================================================================================
%% API functions
%%================================================================================

-doc """
Mria callback that is executed on autoheal.
""".
on_autoheal({_Majority, _Minorities} = PartitionView) ->
    Nodes = emqx:cluster_nodes(running),
    emqx_broker_heal_proto_v1:start(Nodes, PartitionView),
    ok.

-doc """
Start a process that will cause all local channels to renew their registrations in the cm_registry.
""".
-spec start_local({[node()], [[node()]]}) -> ok | {error, _}.
start_local(_) ->
    emqx_broker_sup:start_heal().

%%================================================================================
%% behavior callbacks
%%================================================================================

-record(s, {iterator :: ets:continuation()}).

init(_) ->
    process_flag(trap_exit, true),
    BatchSize = batch_size(),
    MS = {{'_', '$1'}, [], ['$1']},
    case ets:select(?CHAN_TAB, [MS], BatchSize) of
        '$end_of_table' ->
            ignore;
        {Batch, Cont} ->
            emqx_alarm:safe_activate(?alarm, #{}, "Broker is recovering after a network partition"),
            S = #s{iterator = Cont},
            {ok, S, {continue, {first_batch, Batch}}}
    end.

handle_continue({first_batch, Batch}, S) ->
    %% Add random sleep to spread out load generated by multiple nodes over time:
    timer:sleep(rand:uniform(interval())),
    process_batch(Batch),
    {noreply, S}.

handle_call(_Call, _From, S) ->
    {reply, {error, unknown_call}, S}.

handle_cast(_Cast, S) ->
    {noreply, S}.

handle_info(?to_next, S = #s{iterator = It0}) ->
    case ets:match(It0) of
        {Batch, It} ->
            process_batch(Batch),
            {noreply, S#s{iterator = It}};
        '$end_of_table' ->
            {stop, normal, S}
    end;
handle_info({'EXIT', _, shutdown}, S) ->
    {stop, shutdown, S};
handle_info(_Info, S) ->
    {noreply, S}.

terminate(_Reason, _S) ->
    emqx_alarm:ensure_deactivated(?alarm),
    ok.

%%================================================================================
%% Internal exports
%%================================================================================

-spec start_link() -> {ok, pid()}.
start_link() ->
    gen_server:start_link({local, ?SERVER}, ?MODULE, [], []).

%%================================================================================
%% Internal functions
%%================================================================================

process_batch(Chans) ->
    [Pid ! heal_cluster_partition || Pid <- Chans],
    %% Interval can be adjusted dynamically. It's multiplied by the
    %% number of nodes to slow down the rate in very large clusters:
    Interval = interval(),
    erlang:send_after(Interval, self(), ?to_next).

-spec batch_size() -> pos_integer().
batch_size() ->
    emqx_config:get([broker, heal, batch_size]).

-spec interval() -> pos_integer().
interval() ->
    NNodes = max(1, length(emqx:cluster_nodes(running))),
    emqx_config:get([broker, heal, interval]) * NNodes.
