bind :: 0.0.0.0
port 26379
protected-mode no
daemonize no
aclfile /usr/local/etc/redis/sentinel-users.acl

loglevel notice
logfile ""

sentinel resolve-hostnames yes
sentinel monitor mymaster redis-sentinel-master-auth 6379 1
sentinel auth-user mymaster redis_user
sentinel auth-pass mymaster redis-password
sentinel down-after-milliseconds mymaster 10000
sentinel failover-timeout mymaster 20000
