handlers=java.util.logging.ConsoleHandler

.level=FINEST

java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

com.google.cloud.pubsub.level=FINEST
io.gapi.emulators.level=FINEST
io.grpc.level=FINEST
io.netty.level=FINEST

org.slf4j.simpleLogger.defaultLogLevel=trace
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.showThreadName=true
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.log.io.grpc=trace
org.slf4j.simpleLogger.log.io.netty=trace
org.slf4j.simpleLogger.log.io.gapi.emulators=trace
