upstream gcp_emulator_pubsub {
  server gcp_emulator_pubsub:8085 fail_timeout=1s max_fails=3;
}

server {
  listen 8085;
  error_log /tmp/nginx.log debug;
  http2 on;
  location / {
    proxy_pass http://gcp_emulator_pubsub/;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
  }
}
