ConsumerClaim DEFINITIONS AUTOMATIC TAGS ::=
BEGIN
  -- Pid of the consumer process
  ConsumerRef ::= OCTET STRING

  LastSeenTimestamp ::= INTEGER

  ConsumerClaimV1 ::= SEQUENCE {
    consumerRef ConsumerRef,
    lastSeenTimestamp LastSeenTimestamp,
    tombstone BOOLEAN
  }

  ConsumerClaim ::= CHOICE {
    v1 ConsumerClaimV1,
    ...
  }
END
