%%--------------------------------------------------------------------
%% Copyright (c) 2021-2026 EMQ Technologies Co., Ltd. All Rights Reserved.
%%--------------------------------------------------------------------

-module(emqx_authn_password_hashing).

-moduledoc """
Defines password hashing schemas and operations for built-in authentication.

Autogenerated passwords only allow SHA-256 without a salt:

```erlang
#{name => sha256, salt_position => disable}
```

Manually supplied passwords in the legacy profile accept wider variety of simple settings,
bcrypt, and PBKDF2 settings:

```erlang
#{name => sha256, salt_position => prefix}
#{name => bcrypt, salt_rounds => 10}
#{name => pbkdf2, mac_fun => sha, iterations => 10000}
```

Manually supplied passwords in the hardened profile accept SHA-256, SHA-512,
and PBKDF2 with safe mac functions. Being insecure for human-entered manual passwords,
SHA hashes are intended for high-entropy password generation on the client side.

```erlang
#{name => sha512, salt_position => prefix}
#{name => pbkdf2, mac_fun => sha256, iterations => 600000}
#{name => pbkdf2, mac_fun => sha512, iterations => 220000, dk_length => 64}
```
""".

-include_lib("typerefl/include/types.hrl").
-include_lib("hocon/include/hoconsc.hrl").
-include_lib("emqx_auth/include/emqx_authn.hrl").

-type simple_algorithm_name() :: plain | md5 | sha | sha256 | sha512.
-type salt_position() :: disable | prefix | suffix.

-type simple_algorithm() :: #{
    name := simple_algorithm_name(),
    salt_position := salt_position()
}.

-type bcrypt_algorithm() :: #{name := bcrypt}.
-type bcrypt_algorithm_rw() :: #{name := bcrypt, salt_rounds := integer()}.

-type pbkdf2_algorithm() :: #{
    name := pbkdf2,
    mac_fun := emqx_passwd:pbkdf2_mac_fun(),
    iterations := pos_integer()
}.

-type algorithm() :: simple_algorithm() | pbkdf2_algorithm() | bcrypt_algorithm().
-type algorithm_rw() :: simple_algorithm() | pbkdf2_algorithm() | bcrypt_algorithm_rw().
-type stored_algorithm() :: #simple{} | #bcrypt{} | #pbkdf2{}.

%%------------------------------------------------------------------------------
%% Hocon Schema
%%------------------------------------------------------------------------------

-behaviour(hocon_schema).

-export([
    roots/0,
    fields/1,
    desc/1,
    namespace/0
]).

-export([
    type_ro/1,
    type_rw/1,
    type_rw_api/1,
    type_builtin_rw/1,
    type_builtin_rw_api/1,
    type_builtin_generated/1
]).

-export([
    init/1,
    encode/1,
    decode/1,
    gen_password/0,
    gen_salt/1,
    hash/2,
    check_password/4
]).

-define(SALT_ROUNDS_MIN, 5).
-define(SALT_ROUNDS_MAX, 10).

namespace() -> "authn_hash".
roots() -> [pbkdf2, bcrypt, bcrypt_rw, bcrypt_rw_api, simple].

fields(bcrypt_rw) ->
    fields(bcrypt) ++
        [
            {salt_rounds, fun bcrypt_salt_rounds/1}
        ];
fields(bcrypt_rw_api) ->
    fields(bcrypt) ++
        [
            {salt_rounds, fun bcrypt_salt_rounds_api/1}
        ];
fields(bcrypt) ->
    [{name, sc(bcrypt, #{required => true, desc => ?DESC("bcrypt_name")})}];
fields(pbkdf2) ->
    [
        {name,
            sc(
                pbkdf2, #{
                    required => true,
                    desc => ?DESC("pbkdf2_name")
                }
            )},
        {mac_fun,
            sc(
                hoconsc:enum([md4, md5, ripemd160, sha, sha224, sha256, sha384, sha512]),
                #{
                    required => true,
                    desc => ?DESC("pbkdf2_mac_fun")
                }
            )},
        {iterations,
            sc(
                pos_integer(),
                #{required => true, desc => ?DESC("pbkdf2_iterations")}
            )},
        {dk_length, fun dk_length/1}
    ];
fields(hardened_builtin_pbkdf2_sha224) ->
    hardened_builtin_pbkdf2_fields(sha224, 600000);
fields(hardened_builtin_pbkdf2_sha256) ->
    hardened_builtin_pbkdf2_fields(sha256, 600000);
fields(hardened_builtin_pbkdf2_sha384) ->
    hardened_builtin_pbkdf2_fields(sha384, 600000);
fields(hardened_builtin_pbkdf2_sha512) ->
    hardened_builtin_pbkdf2_fields(sha512, 220000);
fields(hardened_builtin_simple) ->
    [
        {name,
            sc(
                hoconsc:enum([sha256, sha512]),
                #{required => true, desc => ?DESC("simple")}
            )},
        {salt_position, fun salt_position/1}
    ];
fields(builtin_generated) ->
    [
        {name, sc(sha256, #{required => true, desc => ?DESC("simple")})},
        {salt_position,
            sc(disable, #{required => true, default => disable, desc => ?DESC("salt_position")})}
    ];
fields(simple) ->
    [
        {name,
            sc(
                hoconsc:enum([plain, md5, sha, sha256, sha512]),
                #{required => true, desc => ?DESC("simple")}
            )},
        {salt_position, fun salt_position/1}
    ].

hardened_builtin_pbkdf2_fields(MacFun, DefaultIterations) ->
    [
        {name, sc(pbkdf2, #{required => true, desc => ?DESC("pbkdf2_name")})},
        {mac_fun,
            sc(MacFun, #{required => true, default => MacFun, desc => ?DESC("pbkdf2_mac_fun")})},
        {iterations,
            sc(pos_integer(), #{
                required => true,
                default => DefaultIterations,
                desc => ?DESC("pbkdf2_iterations")
            })},
        {dk_length, fun dk_length/1}
    ].

bcrypt_salt_rounds(converter) -> fun salt_rounds_converter/2;
bcrypt_salt_rounds(Option) -> bcrypt_salt_rounds_api(Option).

bcrypt_salt_rounds_api(type) -> range(?SALT_ROUNDS_MIN, ?SALT_ROUNDS_MAX);
bcrypt_salt_rounds_api(default) -> ?SALT_ROUNDS_MAX;
bcrypt_salt_rounds_api(example) -> ?SALT_ROUNDS_MAX;
bcrypt_salt_rounds_api(desc) -> ?DESC("bcrypt_salt_rounds");
bcrypt_salt_rounds_api(_) -> undefined.

salt_rounds_converter(undefined, _) ->
    undefined;
salt_rounds_converter(I, _) when is_integer(I) ->
    emqx_utils:clamp(I, ?SALT_ROUNDS_MIN, ?SALT_ROUNDS_MAX);
salt_rounds_converter(X, _) ->
    X.

desc(bcrypt_rw) ->
    ?DESC("bcrypt_rw");
desc(bcrypt_rw_api) ->
    desc("bcrypt_rw");
desc(bcrypt) ->
    ?DESC("bcrypt");
desc(pbkdf2) ->
    ?DESC("pbkdf2");
desc(simple) ->
    ?DESC("simple");
desc(builtin_generated) ->
    ?DESC("builtin_generated");
desc(_) ->
    undefined.

salt_position(type) -> {enum, [disable, prefix, suffix]};
salt_position(default) -> prefix;
salt_position(desc) -> ?DESC("salt_position");
salt_position(_) -> undefined.

dk_length(type) ->
    pos_integer();
dk_length(required) ->
    false;
dk_length(desc) ->
    ?DESC("dk_length");
dk_length(_) ->
    undefined.

%% for emqx_authn_mnesia
type_rw(type) ->
    hoconsc:union(rw_refs());
type_rw(desc) ->
    ?DESC("type_rw");
type_rw(Option) ->
    type_ro(Option).

%% for emqx_authn_mnesia API
type_rw_api(type) ->
    hoconsc:union(api_refs());
type_rw_api(desc) ->
    ?DESC("type_rw");
type_rw_api(_) ->
    undefined.

type_builtin_rw(type) ->
    hoconsc:union(builtin_refs(rw));
type_builtin_rw(Option) ->
    type_rw(Option).

type_builtin_rw_api(type) ->
    hoconsc:union(builtin_refs(api));
type_builtin_rw_api(Option) ->
    type_rw_api(Option).

type_builtin_generated(type) ->
    hoconsc:ref(?MODULE, builtin_generated);
type_builtin_generated(Option) ->
    type_rw_api(Option).

builtin_refs(Kind) ->
    case emqx_security_profile:policy(authn_builtin_accept_weak_password_hash) of
        true -> union_selector(Kind);
        false -> hardened_builtin_union_selector()
    end.

hardened_builtin_union_selector() ->
    fun
        (all_union_members) ->
            hardened_builtin_refs();
        ({value, #{<<"name">> := <<"pbkdf2">>, <<"mac_fun">> := <<"sha224">>}}) ->
            [hardened_pbkdf2_ref(<<"sha224">>)];
        ({value, #{<<"name">> := <<"pbkdf2">>, <<"mac_fun">> := <<"sha384">>}}) ->
            [hardened_pbkdf2_ref(<<"sha384">>)];
        ({value, #{<<"name">> := <<"pbkdf2">>, <<"mac_fun">> := <<"sha512">>}}) ->
            [hardened_pbkdf2_ref(<<"sha512">>)];
        ({value, #{<<"name">> := <<"pbkdf2">>}}) ->
            [hardened_pbkdf2_ref(<<"sha256">>)];
        ({value, #{<<"name">> := _}}) ->
            [hardened_simple_ref()];
        ({value, _}) ->
            throw(#{reason => "algorithm_name_missing"})
    end.

hardened_builtin_refs() ->
    [hardened_simple_ref()] ++
        [
            hardened_pbkdf2_ref(MacFun)
         || MacFun <- [<<"sha224">>, <<"sha256">>, <<"sha384">>, <<"sha512">>]
        ].

hardened_pbkdf2_ref(<<"sha224">>) -> hoconsc:ref(?MODULE, hardened_builtin_pbkdf2_sha224);
hardened_pbkdf2_ref(<<"sha384">>) -> hoconsc:ref(?MODULE, hardened_builtin_pbkdf2_sha384);
hardened_pbkdf2_ref(<<"sha512">>) -> hoconsc:ref(?MODULE, hardened_builtin_pbkdf2_sha512);
hardened_pbkdf2_ref(_) -> hoconsc:ref(?MODULE, hardened_builtin_pbkdf2_sha256).

hardened_simple_ref() ->
    hoconsc:ref(?MODULE, hardened_builtin_simple).

rw_refs() ->
    union_selector(rw).

ro_refs() ->
    union_selector(ro).

api_refs() ->
    union_selector(api).

sc(Type, Meta) -> hoconsc:mk(Type, Meta).

union_selector(Kind) ->
    fun
        (all_union_members) -> refs(Kind);
        ({value, #{<<"name">> := <<"bcrypt">>}}) -> [bcrypt_ref(Kind)];
        ({value, #{<<"name">> := <<"pbkdf2">>}}) -> [pbkdf2_ref(Kind)];
        ({value, #{<<"name">> := _}}) -> [simple_ref(Kind)];
        ({value, _}) -> throw(#{reason => "algorithm_name_missing"})
    end.

refs(Kind) ->
    [
        bcrypt_ref(Kind),
        pbkdf2_ref(Kind),
        simple_ref(Kind)
    ].

pbkdf2_ref(_) ->
    hoconsc:ref(?MODULE, pbkdf2).

bcrypt_ref(rw) ->
    hoconsc:ref(?MODULE, bcrypt_rw);
bcrypt_ref(api) ->
    hoconsc:ref(?MODULE, bcrypt_rw_api);
bcrypt_ref(_) ->
    hoconsc:ref(?MODULE, bcrypt).

simple_ref(_) ->
    hoconsc:ref(?MODULE, simple).

%% for other authn resources
type_ro(type) ->
    hoconsc:union(ro_refs());
type_ro(default) ->
    #{<<"name">> => sha256, <<"salt_position">> => prefix};
type_ro(desc) ->
    ?DESC("type_ro");
type_ro(_) ->
    undefined.

%%------------------------------------------------------------------------------
%% APIs
%%------------------------------------------------------------------------------

-spec encode(algorithm_rw()) -> stored_algorithm().
encode(#{name := bcrypt, salt_rounds := SaltRounds}) ->
    #bcrypt{salt_rounds = SaltRounds};
encode(#{name := pbkdf2, mac_fun := MacFun, iterations := Iterations} = Algorithm) ->
    #pbkdf2{
        mac_fun = MacFun,
        iterations = Iterations,
        dk_length = maps:get(dk_length, Algorithm, undefined)
    };
encode(#{name := Name, salt_position := SaltPosition}) ->
    #simple{name = Name, salt_position = SaltPosition}.

-spec decode(stored_algorithm()) -> algorithm_rw().
decode(#bcrypt{salt_rounds = SaltRounds}) ->
    #{name => bcrypt, salt_rounds => SaltRounds};
decode(#pbkdf2{mac_fun = MacFun, iterations = Iterations, dk_length = undefined}) ->
    #{name => pbkdf2, mac_fun => MacFun, iterations => Iterations};
decode(#pbkdf2{mac_fun = MacFun, iterations = Iterations, dk_length = DKLength}) ->
    #{name => pbkdf2, mac_fun => MacFun, iterations => Iterations, dk_length => DKLength};
decode(#simple{name = Name, salt_position = SaltPosition}) ->
    #{name => Name, salt_position => SaltPosition}.

-spec init(algorithm()) -> ok.
init(#{name := bcrypt}) ->
    {ok, _} = application:ensure_all_started(bcrypt),
    ok;
init(#{name := _Other}) ->
    ok.

-spec gen_salt(algorithm_rw()) -> emqx_passwd:salt().
gen_password() ->
    emqx_base62:encode(crypto:strong_rand_bytes(32)).

gen_salt(#{name := plain}) ->
    <<>>;
gen_salt(#{
    name := bcrypt,
    salt_rounds := Rounds
}) ->
    {ok, Salt} = bcrypt:gen_salt(Rounds),
    list_to_binary(Salt);
gen_salt(#{name := Other}) when Other =/= plain, Other =/= bcrypt ->
    <<X:128/big-unsigned-integer>> = crypto:strong_rand_bytes(16),
    iolist_to_binary(io_lib:format("~32.16.0b", [X])).

-spec hash(algorithm_rw(), emqx_passwd:password()) ->
    {emqx_passwd:password_hash(), emqx_passwd:salt()}.
hash(#{name := bcrypt, salt_rounds := _} = Algorithm, Password) ->
    Salt0 = gen_salt(Algorithm),
    Hash = emqx_passwd:hash({bcrypt, Salt0}, Password),
    Salt = Hash,
    {Hash, Salt};
hash(
    #{
        name := pbkdf2,
        mac_fun := MacFun,
        iterations := Iterations
    } = Algorithm,
    Password
) ->
    Salt = gen_salt(Algorithm),
    DKLength = maps:get(dk_length, Algorithm, undefined),
    Hash = emqx_passwd:hash({pbkdf2, MacFun, Salt, Iterations, DKLength}, Password),
    {Hash, Salt};
hash(#{name := Other, salt_position := SaltPosition} = Algorithm, Password) ->
    Salt =
        case SaltPosition of
            disable -> <<>>;
            _ -> gen_salt(Algorithm)
        end,
    Hash = emqx_passwd:hash({Other, Salt, SaltPosition}, Password),
    {Hash, Salt}.

-spec check_password(
    algorithm(),
    emqx_passwd:salt(),
    emqx_passwd:password_hash(),
    emqx_passwd:password()
) -> boolean().
check_password(#{name := bcrypt}, _Salt, PasswordHash, Password) ->
    emqx_passwd:check_pass({bcrypt, PasswordHash}, PasswordHash, Password);
check_password(
    #{
        name := pbkdf2,
        mac_fun := MacFun,
        iterations := Iterations
    } = Algorithm,
    Salt,
    PasswordHash,
    Password
) ->
    DKLength = maps:get(dk_length, Algorithm, undefined),
    emqx_passwd:check_pass({pbkdf2, MacFun, Salt, Iterations, DKLength}, PasswordHash, Password);
check_password(#{name := Other, salt_position := SaltPosition}, Salt, PasswordHash, Password) ->
    emqx_passwd:check_pass({Other, Salt, SaltPosition}, PasswordHash, Password).
