#!/usr/bin/env escript

%% NOTE: this script should be executed at project root, after the
%% check profile is compiled (any built lib dir can be passed as the
%% first argument instead).
%%
%% Check that no new `emqx_cluster_rpc:multicall' target is added
%% without an explicit exemption.
%%
%% Why this check exists:
%%
%% `emqx_cluster_rpc:multicall' appends the MFA to the cluster_rpc log.
%% A node that boots after downtime does not replay the log entries it
%% missed: `emqx_conf_app:init_load/1' copies the cluster config from a
%% peer and `emqx_cluster_rpc:maybe_init_tnx_id/2' fast-forwards the
%% node's commit pointer past them. Any MFA effect that is not
%% recoverable from the copied config or from a replicated mria table
%% is silently lost on that node.
%%
%% Rules for a multicall target:
%%   - Config updates (`emqx:update_config' and friends) are safe: the
%%     boot-time config copy recovers them.
%%   - Any other target must write durable state to config or mria
%%     BEFORE the multicall, and use the MFA only to rebuild node-local
%%     runtime state. A skipped replay is then harmless because boot
%%     rebuilds runtime state from the replicated data. See
%%     `emqx_topic_metrics_registry' for the reference pattern and
%%     `emqx_mt_config' for another compliant example.
%%
%% If a new target follows these rules, add `{Module, Function}' to
%% ?EXEMPTIONS below with a comment explaining why a skipped replay is
%% safe. Remove entries whose call sites are gone.
%%
%% How it works: xref over the compiled release yields every caller of
%% `emqx_cluster_rpc:multicall/3,5'; the caller's `bpapi_meta/0'
%% (generated by the `emqx_bpapi_trans' parse transform, which only
%% accepts literal target atoms) yields the target MFA.
%%
%% In-tree plugins are part of the scope: the check profile builds
%% without plugins/*, so this script loads the plugin beams from the
%% release-profile build tree (plugins are umbrella apps there; run
%% 'make emqx-enterprise-compile' to produce them) and adds them to
%% the xref graph. Plugins must not use `emqx_cluster_rpc' at all:
%% their MFAs are not replayed on a rebooted node, and their code may
%% not even be loaded when catch-up runs — any plugin caller is
%% reported as a violation.

-mode(compile).

-define(XREF, cluster_rpc_mfa_check).
-define(DEFAULT_RELDIR, "_build/check/lib").
-define(DEFAULT_PLUGIN_LIBDIR, "_build/emqx-enterprise/lib").

%% Safe by design: the boot-time cluster config copy recovers the
%% effect of these targets on a node that missed them.
-define(CONFIG_TARGETS, [
    {emqx, update_config},
    {emqx, remove_config},
    {emqx, reset_config}
]).

%% Grandfathered or audited targets. Each entry needs a reason.
-define(EXEMPTIONS, [
    %% KNOWN DEFECT: plugin package delete / start / stop is lost on a
    %% node that reboots after missing the transaction. The plugin
    %% survives on disk there and resurfaces in the cluster-wide API.
    %% Do not copy this pattern.
    {emqx_mgmt_api_plugins, delete_package},
    {emqx_mgmt_api_plugins, ensure_action},
    %% Audited safe: durable state goes to mria first; these MFAs only
    %% rebuild persistent_term limiter groups, and boot re-derives them
    %% via `emqx_mt_config:load/0'.
    {emqx_mt_config, execute_side_effects_v1},
    {emqx_mt_config, cleanup_managed_ns_configs_v1},
    %% Legacy `emqx_resource_proto_v1' targets: no live callers; the
    %% proto module is kept for RPC compatibility with old peers.
    {emqx_resource, create_local},
    {emqx_resource, create_dry_run_local},
    {emqx_resource, recreate_local},
    {emqx_resource, remove_local},
    %% Metrics resets: a skipped replay loses only a counter reset.
    {emqx_resource, reset_metrics_local},
    {emqx_rule_engine, reset_metrics_for_rule}
]).

main(Args) ->
    {RelDir, PluginLibDir} =
        case Args of
            [Dir, PluginDir] -> {Dir, PluginDir};
            [Dir] -> {Dir, ?DEFAULT_PLUGIN_LIBDIR};
            [] -> {?DEFAULT_RELDIR, ?DEFAULT_PLUGIN_LIBDIR}
        end,
    EbinDirs = filelib:wildcard(filename:join(RelDir, "*/ebin")),
    EbinDirs =/= [] orelse die("no applications found in ~s; compile first~n", [RelDir]),
    PluginEbinDirs = plugin_ebin_dirs(RelDir, PluginLibDir),
    %% The beams must be loadable to read bpapi_meta/0:
    ok = code:add_paths(EbinDirs ++ PluginEbinDirs),
    Callers = find_multicall_callers(RelDir, PluginEbinDirs),
    {Violations, Targets} = lists:foldl(fun collect/2, {[], []}, Callers),
    Stale = ?EXEMPTIONS -- Targets,
    ok = lists:foreach(fun report_violation/1, lists:reverse(Violations)),
    ok = lists:foreach(fun report_stale/1, Stale),
    case {Violations, Stale} of
        {[], []} ->
            io:format("OK~n");
        _ ->
            io:format(standard_error, "~nSee the notes on top of ~s~n", [escript:script_name()]),
            halt(1)
    end.

%% The in-tree plugins are not part of the check profile build: load
%% their beams from the release-profile build tree, where they are
%% umbrella apps. A plugin that is already present in the analyzed lib
%% dir is skipped (its beams are covered by add_release).
plugin_ebin_dirs(RelDir, PluginLibDir) ->
    lists:filtermap(
        fun(PluginDir) ->
            Name = filename:basename(PluginDir),
            case
                not filelib:is_dir(PluginDir) orelse
                    filelib:is_dir(filename:join([RelDir, Name, "ebin"]))
            of
                true ->
                    false;
                false ->
                    EbinDir = filename:join([PluginLibDir, Name, "ebin"]),
                    filelib:wildcard(filename:join(EbinDir, "*.beam")) =/= [] orelse
                        die(
                            "no beams for plugin ~s in ~s;"
                            " run 'make emqx-enterprise-compile' first~n",
                            [Name, EbinDir]
                        ),
                    {true, EbinDir}
            end
        end,
        filelib:wildcard("plugins/*")
    ).

find_multicall_callers(RelDir, PluginEbinDirs) ->
    {ok, _} = xref:start(?XREF),
    ok = xref:set_default(?XREF, [{warnings, false}]),
    {ok, _} = xref:add_release(?XREF, RelDir),
    ok = lists:foreach(
        fun(Dir) -> {ok, _} = xref:add_directory(?XREF, Dir) end,
        PluginEbinDirs
    ),
    Query = "XC || [emqx_cluster_rpc:multicall/3, emqx_cluster_rpc:multicall/5]",
    case xref:q(?XREF, Query) of
        {ok, Pairs} ->
            lists:usort([
                Caller
             || {Caller = {M, _, _}, _Callee} <- Pairs, M =/= emqx_cluster_rpc
            ]);
        {error, xref_compiler, {unknown_constant, Const}} ->
            die("~s is not in the analyzed release ~s; wrong lib dir?~n", [Const, RelDir])
    end.

%% Resolve a multicall caller to its target {M, F} via the metadata
%% that `emqx_bpapi_trans' generated for the proto module.
collect(Caller = {M, F, A}, {Violations, Targets}) ->
    case catch M:bpapi_meta() of
        #{calls := Calls} ->
            case
                [
                    {TM, TF}
                 || {{FM, FF, FArgs}, {TM, TF, _TArgs}} <- Calls,
                    FM =:= M,
                    FF =:= F,
                    length(FArgs) =:= A
                ]
            of
                [] ->
                    {[{no_meta_entry, Caller} | Violations], Targets};
                CallerTargets ->
                    New = [T || T <- CallerTargets, not is_allowed(T)],
                    {
                        [{new_target, T, Caller} || T <- New] ++ Violations,
                        CallerTargets ++ Targets
                    }
            end;
        _ ->
            {[{not_a_proto_module, Caller} | Violations], Targets}
    end.

is_allowed(Target) ->
    lists:member(Target, ?CONFIG_TARGETS ++ ?EXEMPTIONS).

report_violation({new_target, {M, F}, {CM, CF, CA}}) ->
    io:format(
        standard_error,
        "new emqx_cluster_rpc:multicall target ~p:~p (called from ~p:~p/~p); "
        "a node that reboots after missing this transaction will not replay it~n",
        [M, F, CM, CF, CA]
    );
report_violation({not_a_proto_module, {M, F, A}}) ->
    io:format(
        standard_error,
        "~p:~p/~p calls emqx_cluster_rpc:multicall but is not a BPAPI proto module~n",
        [M, F, A]
    );
report_violation({no_meta_entry, {M, F, A}}) ->
    io:format(
        standard_error,
        "cannot determine the emqx_cluster_rpc:multicall target of ~p:~p/~p "
        "from its bpapi_meta/0~n",
        [M, F, A]
    ).

report_stale({M, F}) ->
    io:format(
        standard_error,
        "stale exemption ~p:~p has no call site; remove it from this script~n",
        [M, F]
    ).

die(Fmt, Args) ->
    io:format(standard_error, Fmt, Args),
    halt(1).
