-define(ERR_NO_SERVER_AVAILABLE, no_server_available).
-define(ERR_TIMEOUT, timeout).
-define(ERR_INVALID_JSON, invalid_json).
-define(ERR_SEND_TO_MCP_SERVER_FAILED, send_to_mcp_server_failed).
-define(ERR_INVALID_SERVER_RESPONSE, invalid_server_response).
-define(ERR_WRONG_SERVER_RESPONSE_ID, wrong_server_response_id).
-define(ERR_MALFORMED_JSON_RPC, malformed_json_rpc).
-define(ERR_UNEXPECTED_METHOD, unexpected_method).

-define(ERR_C_NO_SERVER_AVAILABLE, -32000).
-define(ERR_C_TIMEOUT, -32001).
-define(ERR_C_INVALID_JSON, -32002).
-define(ERR_C_SEND_TO_MCP_SERVER_FAILED, -32003).
-define(ERR_C_INVALID_SERVER_RESPONSE, -32004).
-define(ERR_C_WRONG_SERVER_RESPONSE_ID, -32005).
-define(ERR_C_MALFORMED_JSON_RPC, -32006).
-define(ERR_C_UNEXPECTED_METHOD, -32007).

-define(ERR_CODE(ERR),
    case ERR of
        ?ERR_NO_SERVER_AVAILABLE -> ?ERR_C_NO_SERVER_AVAILABLE;
        ?ERR_TIMEOUT -> ?ERR_C_TIMEOUT;
        ?ERR_INVALID_JSON -> ?ERR_C_INVALID_JSON;
        ?ERR_SEND_TO_MCP_SERVER_FAILED -> ?ERR_C_SEND_TO_MCP_SERVER_FAILED;
        ?ERR_INVALID_SERVER_RESPONSE -> ?ERR_C_INVALID_SERVER_RESPONSE;
        ?ERR_WRONG_SERVER_RESPONSE_ID -> ?ERR_C_WRONG_SERVER_RESPONSE_ID;
        ?ERR_MALFORMED_JSON_RPC -> ?ERR_C_MALFORMED_JSON_RPC;
        ?ERR_UNEXPECTED_METHOD -> ?ERR_C_UNEXPECTED_METHOD
    end
).
