name: Build EMQX Marketplace AMI

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  create-aws-ami-for-marketplace:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      ## Set AWS credentials for download package
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download emqx-enterprise package
        id: download
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET }}/emqx-ee/${{ github.ref_name }}/ . --recursive --exclude "*" --include "emqx-enterprise-*-ubuntu22.04-${{ matrix.arch }}.deb"
          find ${{ github.workspace }} -name "emqx-enterprise-*-ubuntu22.04-${{ matrix.arch }}.deb" -exec echo "emqx_file_path={}" \; >> $GITHUB_OUTPUT

      ## Set AWS credentials for create AMI
      - uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722 # v4.1.0
        with:
          aws-access-key-id: ${{ vars.CLOUD_AWS_MARKETPLACE_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CLOUD_AWS_MARKETPLACE_SECRET_KEY }}
          aws-region: us-east-1

      - name: Create AWS AMI
        working-directory: deploy/packer
        id: build
        run: |
          set -eux

          packer init -upgrade .
          packer build -machine-readable --force \
            -var arch=${{ matrix.arch }} \
            -var emqx_version=${GITHUB_REF_NAME#e} \
            -var emqx_package_file_path=${{ steps.download.outputs.emqx_file_path }} \
            . | tee ${{ github.workspace }}/build.log

          echo "ami_id=$(egrep 'artifact,0,id' ${{ github.workspace }}/build.log | rev | cut -f1 -d, | rev)" >> $GITHUB_OUTPUT

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        if: always()
        env:
          SLACK_WEBHOOK: ${{ secrets.CLOUD_AWS_MARKETPLACE_CHANNEL_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: "AWS AMI Build"
          SLACK_MESSAGE: |
            Build of EMQX AMI for AWS Marketplace is ${{ job.status }}.
            - *AMI ID:* ${{ steps.build.outputs.ami_id }}
            - *EMQX Version:* ${{ github.ref_name }}
            - *Architecture:* ${{ matrix.arch }}
          SLACKIFY_MARKDOWN: true
