name: Build slim packages

concurrency:
  group: slim-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      ref:
        required: false

permissions:
  contents: read

jobs:
  plugins-linux-amd64:
    runs-on: ${{ github.repository_owner == 'emqx' && 'aws-ubuntu22.04-amd64' || 'ubuntu-22.04' }}
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        ref: ${{ github.event.inputs.ref }}
        fetch-depth: 0
    - name: Set up environment
      id: env
      run: |
        source env.sh
        echo "BUILDER=$EMQX_DOCKER_BUILD_FROM" >> "$GITHUB_OUTPUT"
    - name: build plugins in builder
      env:
        BUILDER: ${{ steps.env.outputs.BUILDER }}
      run: |
        docker run --rm \
          -v "$PWD:/emqx" \
          -w /emqx \
          "$BUILDER" \
          bash -lc "git config --global --add safe.directory /emqx && make plugins"
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: "plugins"
        path: _build/plugins/*.tar.gz
        retention-days: 7
        compression-level: 0

  linux:
    runs-on: ${{ github.repository_owner == 'emqx' && format('aws-ubuntu22.04-{0}', matrix.profile[2]) || (matrix.profile[2] == 'arm64' && 'ubuntu-22.04-arm' || 'ubuntu-22.04') }}
    env:
      PROFILE: ${{ matrix.profile[0] }}
      ELIXIR: ${{ matrix.profile[1] == 'elixir' && 'yes' || 'no' }}
      ARCH: ${{ matrix.profile[2] }}
      BUILDER_SYSTEM: force_docker

    strategy:
      fail-fast: false
      matrix:
        profile:
          - ["emqx-enterprise", "elixir", "arm64"]
          - ["emqx-enterprise", "erlang", "amd64"]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: build tgz
      run: |
        ./scripts/buildx.sh --profile $PROFILE --pkgtype tgz --elixir $ELIXIR --arch $ARCH
    - name: build pkg
      run: |
        ./scripts/buildx.sh --profile $PROFILE --pkgtype pkg --elixir $ELIXIR --arch $ARCH
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: "${{ matrix.profile[0] }}-${{ matrix.profile[1] }}-${{ matrix.profile[2] }}"
        path: _packages/${{ matrix.profile[0] }}/*
        retention-days: 7
        compression-level: 0

  mac:
    strategy:
      fail-fast: false
      matrix:
        profile:
        - emqx-enterprise
        os:
        - macos-15

    runs-on: ${{ matrix.os }}
    env:
      EMQX_NAME: ${{ matrix.profile }}

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Set up environment
      id: env
      run: |
        source env.sh
        echo "OTP_VSN=$OTP_VSN" >> "$GITHUB_OUTPUT"
        echo "ELIXIR_VSN=$ELIXIR_VSN" >> "$GITHUB_OUTPUT"
    - uses: ./.github/actions/package-macos
      with:
        profile: ${{ matrix.profile }}
        otp: ${{ steps.env.outputs.OTP_VSN }}
        elixir: ${{ steps.env.outputs.ELIXIR_VSN }}
        os: ${{ matrix.os }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ matrix.os }}
        path: _packages/**/*
        retention-days: 7
