name: Spellcheck

concurrency:
  group: spellcheck-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: "emqx-enterprise-schema-dump"
      - name: Run spellcheck
        run: |
          bash scripts/spellcheck/spellcheck.sh _build/docgen/emqx-enterprise/schema-en.json
